---
# tasks file for k8s
- name: Select k3s_cluster_init server
  set_fact:
    k3s_cluster_init_server: '{{ groups["k3s_cluster_init"] | first }}'
  run_once: true

- name: Create dirs
  import_tasks: dirs.yml
  
- name: download executable file
  import_tasks: downloadExecutableFile.yml

- name: Stopped systemd service before install k3s 
  import_tasks: beforeInstall.yml
  when: ansible_os_family == 'RedHat'

- name: Create files
  import_tasks: files.yml

- name: Create configs
  import_tasks: config.yml

- name: Enable and start k3s service
  systemd:
    name: "{{ k3s_service }}" 
    enabled: yes
    state: started
    daemon_reload: yes